### ISSUE TITLE
pylsd and glustick package confilication error,  in pip install -r requiremnts.txt

### ISSUE THREAD

**Issue by YungChenLin** [cvg/VP-Estimation-with-Prior-Gravity#4]
Editor: VScode
host: windows 10 pro
container:  Docker file: FROM ubuntu:jammy
python version in python virtual environment  : python 3.10 

Hi,
   After I install ceres and eigen in ubuntu, I go into the src code and use a virtual environment of python 3.10
   to install requirements, I met an error when running line:25 in  README.md, " **pip install -r requirements.txt "**:
    the following is the error messages: 
       ERROR: Cannot install -r requirements.txt (line 33) and pytlsd 0.0.4 (from git+https://github.com/iago-suarez/pytlsd.git#egg=pytlsd) because these package versions have conflicting dependencies.
  
  The conflict is caused by:
      The user requested pytlsd 0.0.4 (from git+https://github.com/iago-suarez/pytlsd.git#egg=pytlsd)
      gluestick 0.0.0 depends on pytlsd 0.0.4 (from git+https://github.com/iago-suarez/pytlsd.git@37ac583)
  
  To fix this you could try to:
  1. loosen the range of package versions you've specified
  2. remove package versions to allow pip attempt to solve the dependency conflict
  
  ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

I have tried modifying the  last 3 line in the requirements.txt :
    pytlsd@git+https://github.com/iago-suarez/pytlsd.git@37ac583
    -e git+https://github.com/cvg/DeepLSD.git#egg=deeplsd
    -e git+https://github.com/cvg/GlueStick.git#egg=gluestick

but still got errors:

     Building wheel for pytlsd (pyproject.toml) ... error
     error: subprocess-exited-with-error
  
  × Building wheel for pytlsd (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [118 lines of output]
      running bdist_wheel
      running build
      running build_ext
      -- The C compiler identification is GNU 11.4.0
      -- The CXX compiler identification is GNU 11.4.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Deprecation Warning at pybind11/CMakeLists.txt:8 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      
      -- pybind11 v2.10.4
      CMake Warning (dev) at pybind11/tools/FindPythonLibsNew.cmake:98 (find_package):
        Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
        are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
        the cmake_policy command to set the policy and suppress this warning.
      
      Call Stack (most recent call first):
        pybind11/tools/pybind11Tools.cmake:50 (find_package)
        pybind11/tools/pybind11Common.cmake:180 (include)
        pybind11/CMakeLists.txt:208 (include)
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      -- Found PythonInterp: /workspaces/calc_gravity_dir/.env_est_gravity/bin/python3.10 (found suitable version "3.10.12", minimum required is "3.6")
      -- Found PythonLibs: python3.10
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      --     OpenCV_DIR: /usr/local/lib/cmake/opencv4
      --     OpenCV_INCLUDE_DIRS: /usr/local/include/opencv4
      --     OpenCV_LIBS: opencv_calib3dopencv_coreopencv_dnnopencv_features2dopencv_flannopencv_gapiopencv_highguiopencv_imgcodecsopencv_imgprocopencv_mlopencv_objdetectopencv_photoopencv_stitchingopencv_videoopencv_videoio
      --     OpenCV_DIR: /usr/local/lib/cmake/opencv4
      --     OpenCV_INCLUDE_DIRS: /usr/local/include/opencv4
      --     OpenCV_LIBS: opencv_calib3dopencv_coreopencv_dnnopencv_features2dopencv_flannopencv_gapiopencv_highguiopencv_imgcodecsopencv_imgprocopencv_mlopencv_objdetectopencv_photoopencv_stitchingopencv_videoopencv_videoioopencv_calib3dopencv_coreopencv_dnnopencv_features2dopencv_flannopencv_gapiopencv_highguiopencv_imgcodecsopencv_imgprocopencv_mlopencv_objdetectopencv_photoopencv_stitchingopencv_videoopencv_videoio
      -- Configuring done (0.4s)
      CMake Error in CMakeLists.txt:
        Imported target "pybind11::module" includes non-existent path
      
          "/usr/include/python3.10"
      
        in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
      
        * The path was deleted, renamed, or moved to another location.
      
        * An install or uninstall procedure did not complete successfully.
      
        * The installation package was faulty and references files it does not
        provide.
      
      
      -- Generating done (0.0s)
      CMake Generate step failed.  Build files cannot be regenerated correctly.
      Traceback (most recent call last):
        File "/workspaces/calc_gravity_dir/.env_est_gravity/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/workspaces/calc_gravity_dir/.env_est_gravity/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/workspaces/calc_gravity_dir/.env_est_gravity/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-06gjzad3/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 404, in build_wheel
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-06gjzad3/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 389, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-06gjzad3/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 65, in <module>
        File "/tmp/pip-build-env-06gjzad3/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-06gjzad3/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-06gjzad3/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-06gjzad3/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-06gjzad3/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-06gjzad3/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-06gjzad3/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/tmp/pip-build-env-06gjzad3/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-06gjzad3/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-06gjzad3/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-06gjzad3/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-06gjzad3/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-06gjzad3/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-06gjzad3/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-06gjzad3/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-06gjzad3/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/tmp/pip-build-env-06gjzad3/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/tmp/pip-build-env-06gjzad3/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "<string>", line 55, in build_extension
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-9ofndmqr/pytlsd_825a1c16d0d64f67b3681539f05fd5c4', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-9ofndmqr/pytlsd_825a1c16d0d64f67b3681539f05fd5c4/build/lib.linux-x86_64-cpython-310/', '-DPYTHON_EXECUTABLE=/workspaces/calc_gravity_dir/.env_est_gravity/bin/python3.10', '-DEXAMPLE_VERSION_INFO=0.0.4', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pytlsd
  Building editable for gluestick (pyproject.toml) ... done
  Created wheel for gluestick: filename=gluestick-0.0.0-0.editable-py3-none-any.whl size=5688 sha256=e2dce999515bef5e7de6380de217e154b9081dfc85dc8cae31171cf76e9d1d4b
  Stored in directory: /tmp/pip-ephem-wheel-cache-v9ns0oim/wheels/21/76/98/7e6c13d375402b61248de409bcd3eb7eba75f184358e9ec8ea
Successfully built gluestick
Failed to build pytlsd
ERROR: Could not build wheels for pytlsd, which is required to install pyproject.toml-based projects

Any suggestions for solving the conflict  ?

THX
BR

**Comment by PladsElsker** [comment]
This was solved for me by creating a new venv, then installing only pytlsd with `pip install -e git+https://github.com/iago-suarez/pytlsd.git#egg=pytlsd` first, and then installing the rest.
